deployment:
  tasks:
    - export DEPLOYPATH=/home/phbearco/shift.ayanozturk.com
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -a * $DEPLOYPATH
    - cd $DEPLOYPATH && /opt/cpanel/composer/bin/composer install --no-interaction
#    - cd $DEPLOYPATH && bin/console doctrine:schema:update -f
    - cd $DEPLOYPATH && bin/console cache:clear
    - cd $DEPLOYPATH && bin/console assets:install public
