build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'

      environment:
        php: 7.4

      tests:
        override:
          - php-scrutinizer-run
          - bin/phpunit
filter:
  excluded_paths:
    - 'bin/*'
    - 'config/*'
checks:
  php: true
