version: '3'

services:

  app:
    build: config/docker
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:80"
    depends_on:
      - database
    environment:
      APP_SECRET: qwerty123

  database:
    image: mysql:5
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: app

