index:
    path: /
    controller: App\Controller\DefaultController::index

create-account:
    path: /account/create
    controller: App\Controller\Account\Onboarding::createAccount

account-details:
    path: /account/details
    controller: App\Controller\Account\AccountController::details

checkout:
    path: /account/checkout
    controller: App\Controller\Account\Onboarding::checkout

shift-list:
    path: /shift/list
    controller: App\Controller\ShiftController::list

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout