index:
    path: /
    controller: App\Controller\DefaultController::index

create-account:
    path: /account/create
    controller: App\Controller\Account\Onboarding::createAccount

account-details:
    path: /account/details
    controller: App\Controller\Account\AccountController::details

account-company:
    path: /account/company
    controller: App\Controller\Account\AccountController::company

change-password:
    path: /user/change-password
    controller: App\Controller\UserController::changePassword

checkout:
    path: /account/checkout
    controller: App\Controller\Account\Onboarding::checkout

shift-list:
    path: /shift/list
    controller: App\Controller\ShiftController::list

shift-create:
    path: /shift/create/{day<\d+>}
    controller: App\Controller\ShiftController::create

shift-calendar:
    path: /shift/calendar
    controller: App\Controller\ShiftController::calendar

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout