index:
    path: /
    controller: App\Controller\DefaultController::index

create-account:
    path: /account/create
    controller: App\Controller\Account\Onboarding::createAccount

checkout:
    path: /account/checkout
    controller: App\Controller\Account\Onboarding::checkout